services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"          # http://localhost:8080
    volumes:
      - ./site:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro